### ISSUE TITLE
AWS S3 Connections have hardcoded bucket name 'zibucket'

### ISSUE THREAD

**Issue by timgabrhel** [StratusOn/S3-to-Blob#1]
https://github.com/StratusOn/S3-to-Blob/blob/master/src/Deployments/azuredeploy.json#L946

https://github.com/StratusOn/S3-to-Blob/blob/master/src/Deployments/azuredeploy.json#L1021

**Comment by raouche** [comment]
Many thanks, @timgabrhel, for trying out this solution and for reporting the hard-coded bucket names bug. The bug has been fixed in the linked commit.
